spring.application.name=core-api
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

spring.data.redis.url=${REDIS_URL}
management.health.redis.enabled=true
spring.session.store-type=redis

management.endpoint.health.access=unrestricted
jwt.secret=${JWT_SECRET:11d45855843b000a40f8ebc19325e9dcc0831d663846598688bb186e603bdcc6}
jwt.expiration-time=${JWT_EXPIRATION:900000}